# Generated by Django 5.1.4 on 2024-12-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookborrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookborrow',
            name='return_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
